<script setup lang="ts">
/* eslint-disable no-alert */
import IdentityList from '~/components/identity/IdentityList.vue'

const { t } = useI18n()

useHydratedHead({
  title: () => `${t('settings.users.label')} | ${t('nav.settings')}`,
})

const loggedInUsers = useUsers()

async function exportTokens() {
  if (import.meta.server)
    return

  if (!confirm('Please aware that the tokens represent the **full access** to your accounts, and should be treated as sensitive information. Are you sure you want to export the tokens?'))
    return

  const { saveAs } = await import('file-saver')
  const data = {
    '/': 'Generated by Elk, you can import it to Elk to restore the tokens.',
    '//': 'This file represents the **full access** to your accounts, and should be treated as sensitive information.',
    'version': 1,
    'origin': location.origin,
    'users': loggedInUsers.value,
  }
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json;charset=utf-8' })
  saveAs(blob, `elk-users-tokens-${new Date().toISOString().slice(0, 10)}.json`)
}
</script>

<template>
  <MainContent back-on-small-screen>
    <template #title>
      <div text-lg font-bold flex items-center gap-2 @click="$scrollToTop">
        <span>{{ $t('settings.users.label') }}</span>
      </div>
    </template>
    <div p6>
      <div class="mb-6">
        <IdentityList />
      </div>

      <template v-if="loggedInUsers.length">
        <div class="mb-4">
          <h2 class="text-xl font-bold mb-4">
            Elk Platform Users
          </h2>
          <div flex="~ col gap2">
            <div v-for="user of loggedInUsers" :key="user.account.id">
              <AccountInfo :account="user.account" :hover-card="false" />
            </div>
          </div>
        </div>
        <div my4 border="t base" />
        <button btn-text flex="~ gap-2" items-center @click="exportTokens">
          <span block i-ri-download-2-line />
          {{ $t('settings.users.export') }}
        </button>
      </template>
    </div>
  </MainContent>
</template>
